#ifndef FLEX_HEADER_CLexer_h
#define FLEX_HEADER_CLexer_h
#define YY_CLexer_CHAR unsigned char
#line 1 "C:\\Users\\L.Falcon\\Desktop\\\37777777724\37777777664\37777777664\37777777772\37777777702\37777777753\\obfusc\\flex_bison\\flexskel.h"
/* A lexical scanner header generated by flex */
/* MODIFIED FOR C++ CLASS BY Alain Coetmeur: coetmeur(at)icdc.fr */
/* Note that (at) mean the 'at' symbol that I cannot write */
/* because it is expanded to the class name */
/* made at Informatique-CDC, Research&development department */
/* company from the Caisse Des Depots et Consignations */


/*********************************************/
/* SYSTEM dependent declaration, includes... */
/*********************************************/
/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif
#ifdef __cplusplus
#ifndef YY_USE_PROTOS
#define YY_USE_PROTOS
#endif
#ifndef YY_USE_CLASS
#define YY_USE_CLASS
#endif
#else	/* ! __cplusplus */
#ifdef __STDC__
#ifdef __GNUC__
#else
#endif	/* __GNUC__ */
#ifndef YY_USE_PROTOS
#define YY_USE_PROTOS
#endif
#endif	/* __STDC__ */
#endif	/* ! __cplusplus */
/*********************************************/
/* COMPILER DEPENDENT   MACROS               */
/*********************************************/
/* use prototypes in function declarations */
#ifndef YY_PROTO
#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif
#endif
#include <stdio.h>




/* % here is the declaration from section1 %header{  */ 
#line 4 "CLexer.l"
#include "pre.h"

#include "CLexer.h"
#include "CParser.h"

#include "ExtraString.h"

#define TAB_COLUMN 4
#define YY_USER_ACTION BeginAction();
#line 15 "CLexer.l"
#define YY_CLexer_INHERIT 
#line 16 "CLexer.l"
#define YY_CLexer_LEX_RETURN  int
#line 17 "CLexer.l"
#define YY_CLexer_LEX  ScanValue
#line 18 "CLexer.l"
#define YY_CLexer_LEX_PARAM  TokenValue &theValue
#line 19 "CLexer.l"
#define YY_CLexer_MEMBERS  \
	protected: \
		int theLine,theColumn; \
		string notValueText; \
		ExtraString *exstr; \
		virtual int check_type(TokenValue &theValue); \
		void comment(); \
		void comment2(); \
		void BeginAction(); \
		void notValue(); \
		void preprocess(); \
		void SetColumnLine4Input(char c); \
		void prestring2exstr();
#line 32 "CLexer.l"
#define YY_CLexer_CONSTRUCTOR_PARAM  void
#line 33 "CLexer.l"
#define YY_CLexer_CONSTRUCTOR_INIT  : theLine(1),theColumn(1)
#line 34 "CLexer.l"
#define YY_CLexer_CONSTRUCTOR_CODE  {exstr=NULL;};
#line 36 "CLexer.l"
#define YY_CLexer_TEXT  theText
#line 37 "CLexer.l"
#define YY_CLexer_LENG  theTextLength
#line 51 "CLexer.l"
#line 52 "C:\\Users\\L.Falcon\\Desktop\\\37777777724\37777777664\37777777664\37777777772\37777777702\37777777753\\obfusc\\flex_bison\\flexskel.h"

#ifdef YY_USE_CLASS
#ifdef YY_CLexer_IOSTREAM
#include <iostream.h>
#define YY_CLexer_IFILE  istream
#define YY_CLexer_OFILE ostream 
#define YY_CLexer_ERRFILE cerr

#ifndef YY_CLexer_IFILE_DEFAULT
#define YY_CLexer_IFILE_DEFAULT &cin
#endif

#ifndef YY_CLexer_OFILE_DEFAULT
#define YY_CLexer_OFILE_DEFAULT &cout
#endif

#endif
#endif

#ifndef YY_CLexer_IFILE
#define YY_CLexer_IFILE FILE 
#endif

#ifndef YY_CLexer_OFILE
#define YY_CLexer_OFILE FILE 
#endif

#ifndef YY_CLexer_ERRFILE
#define YY_CLexer_ERRFILE stderr
#endif

#ifndef YY_CLexer_IFILE_DEFAULT
#define YY_CLexer_IFILE_DEFAULT stdin
#endif

#ifndef YY_CLexer_OFILE_DEFAULT
#define YY_CLexer_OFILE_DEFAULT stdout
#endif




#ifndef YY_CLexer_TEXT
#define YY_CLexer_TEXT yytext
#endif
#ifndef YY_CLexer_LENG
#define YY_CLexer_LENG yyleng
#endif
#ifndef YY_CLexer_IN
#define YY_CLexer_IN yyin
#endif
#ifndef YY_CLexer_OUT
#define YY_CLexer_OUT yyout
#endif

#ifndef YY_CLexer_LEX_RETURN
#define YY_CLexer_LEX_RETURN int
#else
#ifndef YY_CLexer_LEX_DEFINED
#define YY_CLexer_LEX_DEFINED 
#endif
#endif

#ifndef YY_CLexer_LEX
#define YY_CLexer_LEX yylex
#else
#ifndef YY_CLexer_LEX_DEFINED
#define YY_CLexer_LEX_DEFINED 
#endif
#endif

#ifndef YY_CLexer_LEX_PARAM
#ifndef YY_USE_PROTOS
#define YY_CLexer_LEX_PARAM 
#else
#define YY_CLexer_LEX_PARAM void
#endif
#else
#ifndef YY_CLexer_LEX_DEFINED
#define YY_CLexer_LEX_DEFINED 
#endif
#endif

#ifndef YY_CLexer_LEX_PARAM_DEF
#define YY_CLexer_LEX_PARAM_DEF
#else
#ifndef YY_CLexer_LEX_DEFINED
#define YY_CLexer_LEX_DEFINED 
#endif
#endif

#ifndef YY_CLexer_RESTART
#define YY_CLexer_RESTART yyrestart
#endif
#ifndef YY_CLexer_SWITCH_TO_BUFFER
#define YY_CLexer_SWITCH_TO_BUFFER yy_switch_to_buffer
#endif
#ifndef YY_CLexer_LOAD_BUFFER_STATE
#define YY_CLexer_LOAD_BUFFER_STATE yy_load_buffer_state
#endif

#ifndef YY_CLexer_CREATE_BUFFER
#define YY_CLexer_CREATE_BUFFER yy_create_buffer
#ifndef YY_USE_CLASS
#ifndef yy_new_buffer
#define yy_new_buffer yy_create_buffer
#endif
#endif
#endif
#ifndef YY_CLexer_DELETE_BUFFER
#define YY_CLexer_DELETE_BUFFER yy_delete_buffer
#endif
#ifndef YY_CLexer_INIT_BUFFER
#define YY_CLexer_INIT_BUFFER yy_init_buffer
#endif



#ifdef YY_CLexer_FLEX_DEBUG
#ifndef YY_CLexer_DEBUG
#define YY_CLexer_DEBUG 1
#endif
#else
#ifndef YY_CLexer_DEBUG
#define YY_CLexer_DEBUG 0
#endif
#endif

#if YY_CLexer_DEBUG != 0
#ifndef YY_CLexer_DEBUG_FLAG
#define YY_CLexer_DEBUG_FLAG yy_flex_debug
#endif
#ifndef YY_CLexer_DEBUG_INIT
#define YY_CLexer_DEBUG_INIT 1
#endif
#endif




#ifndef YY_USE_CLASS
#ifndef YY_CLexer_CURRENT_BUFFER
#define YY_CLexer_CURRENT_BUFFER yy_current_buffer
#endif
typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern void YY_CLexer_RESTART YY_PROTO(( YY_CLexer_IFILE *input_file ));
extern void YY_CLexer_SWITCH_TO_BUFFER YY_PROTO(( YY_BUFFER_STATE new_buffer ));
extern void YY_CLexer_LOAD_BUFFER_STATE YY_PROTO(( void ));
extern YY_BUFFER_STATE YY_CLexer_CREATE_BUFFER YY_PROTO(( YY_CLexer_IFILE *file, int size ));
extern void YY_CLexer_DELETE_BUFFER YY_PROTO(( YY_BUFFER_STATE b ));
extern void YY_CLexer_INIT_BUFFER YY_PROTO(( YY_BUFFER_STATE b, YY_CLexer_IFILE *file ));

#if YY_CLexer_DEBUG != 0
extern int YY_CLexer_DEBUG_FLAG ;
#endif
extern YY_CLexer_CHAR  *YY_CLexer_TEXT;
extern int YY_CLexer_LENG;
extern YY_CLexer_IFILE *YY_CLexer_IN;
extern YY_CLexer_OFILE *YY_CLexer_OUT;
#ifdef YY_CLexer_LEX_DEFINED
extern YY_CLexer_LEX_RETURN YY_CLexer_LEX ( YY_CLexer_LEX_PARAM )
YY_CLexer_LEX_PARAM_DEF
#else
#ifndef YY_DECL
extern YY_CLexer_LEX_RETURN YY_CLexer_LEX ( YY_CLexer_LEX_PARAM )
YY_CLexer_LEX_PARAM_DEF
#else
/* no declaration if oldstyle flex */
#endif
#endif
#else

#ifndef YY_CLexer_CURRENT_BUFFER
#define YY_CLexer_CURRENT_BUFFER YY_CURRENT_BUFFER
#endif
#ifndef YY_CLexer_CLASS
#define YY_CLexer_CLASS CLexer
#endif
#ifndef YY_CLexer_ECHO
#define YY_CLexer_ECHO yy_echo
#endif
#ifdef YY_CLexer_ECHO_PURE
#define YY_CLexer_ECHO_NOCODE
#endif

#ifndef YY_CLexer_ECHO_CODE
#ifndef YY_CLexer_IOSTREAM
#define YY_CLexer_ECHO_CODE fwrite( (char *) YY_CLexer_TEXT, YY_CLexer_LENG, 1, YY_CLexer_OUT );
#else
#define YY_CLexer_ECHO_CODE (YY_CLexer_OUT->write( (char *) YY_CLexer_TEXT, YY_CLexer_LENG));
#endif
#endif

#ifndef YY_CLexer_INPUT
#define YY_CLexer_INPUT yy_input
#endif
#ifdef YY_CLexer_INPUT_PURE
#define YY_CLexer_INPUT_NOCODE
#endif

#ifndef YY_CLexer_INPUT_CODE
#ifndef YY_CLexer_IOSTREAM
#define YY_CLexer_INPUT_CODE return result= fread(  buffer, 1,max_size,YY_CLexer_IN );
#else
#define YY_CLexer_INPUT_CODE if(YY_CLexer_IN->eof())  result=0;else {YY_CLexer_IN->read(buffer,max_size);result=YY_CLexer_IN->gcount();YY_CLexer_IN->clear(YY_CLexer_IN->rdstate()&(~ios::failbit));if(YY_CLexer_IN->bad()) result= -1;} return result;
#endif
#endif

#ifdef YY_CLexer_FATAL_ERROR_PURE
#define YY_CLexer_FATAL_ERRO_NOCODE
#endif
#ifndef YY_CLexer_FATAL_ERROR
#define YY_CLexer_FATAL_ERROR yy_fatal_error
#endif

#ifndef YY_CLexer_FATAL_ERROR_CODE
#ifndef YY_CLexer_IOSTREAM
#define YY_CLexer_FATAL_ERROR_CODE fputs( msg, YY_CLexer_ERRFILE );putc( '\n', YY_CLexer_ERRFILE );exit( 1 );
#else
#define YY_CLexer_FATAL_ERROR_CODE YY_CLexer_ERRFILE<< msg <<endl;exit( 1 );
#endif
#endif

#ifndef YY_CLexer_WRAP
#define YY_CLexer_WRAP yy_wrap
#endif
#ifdef YY_CLexer_WRAP_PURE
#define YY_CLexer_WRAP_NOCODE
#endif
#ifndef YY_CLexer_WRAP_CODE
#define YY_CLexer_WRAP_CODE return 1;
#endif


#ifndef YY_CLexer_INHERIT
#define YY_CLexer_INHERIT
#endif
#ifndef YY_CLexer_MEMBERS
#define YY_CLexer_MEMBERS 
#endif
#ifndef YY_CLexer_CONSTRUCTOR_PARAM
#define YY_CLexer_CONSTRUCTOR_PARAM
#endif
#ifndef YY_CLexer_CONSTRUCTOR_CODE
#define YY_CLexer_CONSTRUCTOR_CODE
#endif
#ifndef YY_CLexer_CONSTRUCTOR_INIT
#define YY_CLexer_CONSTRUCTOR_INIT
#endif
#ifndef YY_CLexer_DESTRUCTOR_CODE
#define YY_CLexer_DESTRUCTOR_CODE
#endif
typedef struct yy_buffer_state *YY_BUFFER_STATE;

class YY_CLexer_CLASS YY_CLexer_INHERIT
{
 private:/* data */
 YY_CLexer_CHAR  *yy_c_buf_p;
 YY_CLexer_CHAR  yy_hold_char;
 int yy_n_chars;
 int yy_init;
 int yy_start;
 int yy_did_buffer_switch_on_eof;
 private: /* functions */
 void yy_initialize();
 int input();
 int yyinput() {return input();};
 int yy_get_next_buffer();
 void yyunput( YY_CLexer_CHAR  c, YY_CLexer_CHAR  *buf_ptr );
 /* use long instead of yy_state_type because it is undef */
 long yy_get_previous_state_ ( void );
 long yy_try_NUL_trans_  ( long current_state_ );
 protected:/* non virtual */
 YY_BUFFER_STATE YY_CLexer_CURRENT_BUFFER;
 void YY_CLexer_RESTART ( YY_CLexer_IFILE *input_file );
 void YY_CLexer_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer );
 void YY_CLexer_LOAD_BUFFER_STATE( void );
 YY_BUFFER_STATE YY_CLexer_CREATE_BUFFER( YY_CLexer_IFILE *file, int size );
 void YY_CLexer_DELETE_BUFFER( YY_BUFFER_STATE b );
 void YY_CLexer_INIT_BUFFER( YY_BUFFER_STATE b, YY_CLexer_IFILE *file );
 protected: /* virtual */
 virtual void YY_CLexer_ECHO()
#ifdef YY_CLexer_ECHO_PURE
  =0
#endif
  ;
 virtual int  YY_CLexer_INPUT(char  *buf,int &result,int max_size)
#ifdef YY_CLexer_INPUT_PURE
  =0
#endif
  ;
 virtual void  YY_CLexer_FATAL_ERROR(char *msg)
#ifdef YY_CLexer_FATAL_ERROR_PURE
  =0
#endif
  ;
 virtual int  YY_CLexer_WRAP()
#ifdef YY_CLexer_WRAP_PURE
  =0
#endif
  ;
 public:
 YY_CLexer_CHAR  *YY_CLexer_TEXT;
 int YY_CLexer_LENG;
 YY_CLexer_IFILE *YY_CLexer_IN;
 YY_CLexer_OFILE *YY_CLexer_OUT;
 YY_CLexer_LEX_RETURN YY_CLexer_LEX ( YY_CLexer_LEX_PARAM);
 YY_CLexer_CLASS(YY_CLexer_CONSTRUCTOR_PARAM) ;
 virtual ~YY_CLexer_CLASS() ;
#if YY_CLexer_DEBUG != 0
 int YY_CLexer_DEBUG_FLAG;
#endif
 public: /* added members */
 YY_CLexer_MEMBERS 
};
#endif



/* declaration of externs for public use of yylex scanner */

/* % here is the declaration from section2 %header{ */ 
#line 163 "CLexer.l"
#endif
#line 375 "C:\\Users\\L.Falcon\\Desktop\\\37777777724\37777777664\37777777664\37777777772\37777777702\37777777753\\obfusc\\flex_bison\\flexskel.h"

/* end of generated header */
